(function () {
  'use strict';
  var storageKey = 'openmicfm-station-data';
  var initialData = { shows: [{ time: '05:00 – 09:00', name: 'Sunrise Mthatha', presenter: 'Lwazi Ndlovu', initials: 'LN', tone: 'blue' }, { time: '09:00 – 12:00', name: 'The Mid-Morning Mix', presenter: 'Thando Mbeki', initials: 'TM', tone: 'yellow' }, { time: '12:00 – 15:00', name: 'Lunch with Lungile', presenter: 'Lungile Maseko', initials: 'LM', tone: 'green' }, { time: '15:00 – 18:00', name: 'Drive Home', presenter: 'Siyanda Gqoboka', initials: 'SG', tone: 'red' }, { time: '18:00 – 20:00', name: 'The Evening Exchange', presenter: 'Anele Radebe', initials: 'AR', tone: 'blue' }, { time: '20:00 – 22:00', name: 'Open Mic Sessions', presenter: 'Guest rotation', initials: 'GR', tone: 'yellow' }], songs: [{ title: 'Imithandazo', artist: 'Kabza De Small & DJ Maphorisa', plays: 42 }, { title: 'Mnike', artist: 'Tyler ICU ft. Tumelo_za', plays: 38 }, { title: 'Asibe Happy', artist: 'Kabza De Small, DJ Maphorisa', plays: 35 }, { title: 'Amabala', artist: 'Tyla', plays: 31 }, { title: 'Koo Koo Fun', artist: 'Focalistic', plays: 29 }, { title: 'iPlan', artist: 'Daliwonga', plays: 27 }, { title: 'Imizwa', artist: 'Mthandazo Gatya', plays: 24 }, { title: 'Water', artist: 'Tyla', plays: 22 }, { title: 'Ses’fikile', artist: 'Lloyiso', plays: 19 }, { title: 'Saka', artist: 'Busta 929', plays: 16 }], posts: [{ type: 'Local', title: 'New community garden opens its doors in Mthatha', excerpt: 'A new growing space is bringing neighbours together.', date: 'Today, 09:42', status: 'Published' }, { type: 'Sport', title: 'School league finals set for Saturday showdown', excerpt: 'The region’s young stars are ready for a big finish.', date: 'Yesterday', status: 'Published' }, { type: 'National', title: 'Power update: what households need to know', excerpt: 'The latest service update from across the country.', date: '01 Sep 2026', status: 'Published' }, { type: 'Local', title: 'Five local artists to watch this spring', excerpt: 'Fresh voices are making waves across the Eastern Cape.', date: '30 Aug 2026', status: 'Draft' }, { type: 'Sport', title: 'Back on top: Chiefs outclass Sekhukhune', excerpt: 'A confident performance earns a second league win.', date: '29 Aug 2026', status: 'Published' }] };
  var data = JSON.parse(localStorage.getItem(storageKey) || 'null') || initialData;
  var loginView = document.getElementById('login-view');
  var dashboard = document.getElementById('dashboard-view');
  var modal = document.getElementById('modal-backdrop');
  var modalFields = document.getElementById('modal-fields');
  var modalTitle = document.getElementById('modal-title');
  var activeModal = '';
  function persist() { localStorage.setItem(storageKey, JSON.stringify(data)); }
  function escapeHtml(value) { return String(value).replace(/[&<>'"]/g, function (character) { return ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#039;', '"': '&quot;' })[character]; }); }
  function showDashboard() { loginView.hidden = true; dashboard.hidden = false; renderAll(); }
  if (sessionStorage.getItem('openmicfm-auth') === 'true') showDashboard();
  document.getElementById('login-form').addEventListener('submit', function (event) { event.preventDefault(); var email = document.getElementById('login-email').value; var password = document.getElementById('login-password').value; if (email === 'manager@openmicfm.co.za' && password === 'openmic') { sessionStorage.setItem('openmicfm-auth', 'true'); showDashboard(); } else { document.getElementById('login-message').textContent = 'That login does not match the local demo account.'; } });
  document.getElementById('logout-button').addEventListener('click', function () { sessionStorage.removeItem('openmicfm-auth'); dashboard.hidden = true; loginView.hidden = false; });
  function renderAll() { document.getElementById('stat-shows').textContent = data.shows.length; document.getElementById('stat-tracks').textContent = data.songs.length; renderSchedule(); renderMusic(); renderPosts(); }
  function renderSchedule() { var html = data.shows.map(function (show) { return '<div class="schedule-item"><time>' + escapeHtml(show.time) + '</time><div class="presenter"><span class="presenter-avatar">' + escapeHtml(show.initials) + '</span><div><strong>' + escapeHtml(show.name) + '</strong><small>' + escapeHtml(show.presenter) + '</small></div></div><span class="status-pill">Confirmed</span><button class="row-actions" type="button" data-delete-show="' + data.shows.indexOf(show) + '" aria-label="Delete show">···</button></div>'; }).join(''); document.getElementById('schedule-list').innerHTML = html; document.getElementById('overview-schedule').innerHTML = data.shows.slice(0, 4).map(function (show) { return '<div class="schedule-row"><time>' + escapeHtml(show.time.split(' ')[0]) + '</time><div><strong>' + escapeHtml(show.name) + '</strong><small>' + escapeHtml(show.presenter) + '</small></div><span class="status-pill">On air</span></div>'; }).join(''); }
  function renderMusic() { document.getElementById('music-list').innerHTML = data.songs.map(function (song, index) { return '<div class="music-item"><span class="rank">' + String(index + 1).padStart(2, '0') + '</span><div class="track"><strong>' + escapeHtml(song.title) + '</strong><small>Now in rotation</small></div><span>' + escapeHtml(song.artist) + '</span><span class="plays">' + escapeHtml(song.plays) + ' plays</span><button class="row-actions" type="button" data-delete-song="' + index + '" aria-label="Delete song">···</button></div>'; }).join(''); }
  function renderPosts(filter) { var posts = data.posts.filter(function (post) { return !filter || filter === 'all' || post.type.toLowerCase() === filter || (filter === 'draft' && post.status === 'Draft'); }); document.getElementById('news-list').innerHTML = posts.map(function (post) { return '<article class="news-card"><div class="news-card-top"><span class="news-type">' + escapeHtml(post.type) + '</span><span class="' + (post.status === 'Draft' ? 'draft-badge' : '') + '">' + escapeHtml(post.status) + '</span></div><h3>' + escapeHtml(post.title) + '</h3><p>' + escapeHtml(post.excerpt) + '</p><footer><span>' + escapeHtml(post.date) + '</span><button class="text-button" type="button" data-delete-post="' + data.posts.indexOf(post) + '">Remove</button></footer></article>'; }).join(''); document.getElementById('all-count').textContent = data.posts.length + 19; }
  function fieldsFor(type) { if (type === 'show') return '<div class="form-field"><label for="field-time">Time slot</label><input id="field-time" required placeholder="09:00 – 12:00"></div><div class="form-field"><label for="field-name">Show name</label><input id="field-name" required placeholder="The Mid-Morning Mix"></div><div class="form-field full"><label for="field-presenter">Presenter</label><input id="field-presenter" required placeholder="Presenter name"></div>'; if (type === 'song') return '<div class="form-field"><label for="field-title">Song title</label><input id="field-title" required placeholder="Song title"></div><div class="form-field"><label for="field-artist">Artist</label><input id="field-artist" required placeholder="Artist name"></div><div class="form-field"><label for="field-plays">Current plays</label><input id="field-plays" type="number" min="0" value="0" required></div>'; return '<div class="form-field"><label for="field-type">Section</label><select id="field-type"><option>Local</option><option>National</option><option>Sport</option></select></div><div class="form-field"><label for="field-status">Status</label><select id="field-status"><option>Published</option><option>Draft</option></select></div><div class="form-field full"><label for="field-title">Headline</label><input id="field-title" required placeholder="Story headline"></div><div class="form-field full"><label for="field-excerpt">Short summary</label><textarea id="field-excerpt" required placeholder="A short description for the newsroom..."></textarea></div>'; }
  function openModal(type) { activeModal = type; modalTitle.textContent = type === 'show' ? 'Add a show' : type === 'song' ? 'Add a song' : 'New story'; modalFields.innerHTML = fieldsFor(type); modal.hidden = false; modalFields.querySelector('input,select').focus(); }
  function closeModal() { modal.hidden = true; }
  document.getElementById('add-show-button').addEventListener('click', function () { openModal('show'); }); document.getElementById('add-song-button').addEventListener('click', function () { openModal('song'); }); document.getElementById('add-post-button').addEventListener('click', function () { openModal('post'); }); document.getElementById('modal-close').addEventListener('click', closeModal); modal.addEventListener('click', function (event) { if (event.target === modal) closeModal(); });
  document.getElementById('item-form').addEventListener('submit', function (event) { event.preventDefault(); var value = function (id) { return document.getElementById(id).value.trim(); }; if (activeModal === 'show') data.shows.push({ time: value('field-time'), name: value('field-name'), presenter: value('field-presenter'), initials: value('field-presenter').split(' ').map(function (part) { return part[0]; }).join('').slice(0, 2).toUpperCase() }); if (activeModal === 'song') data.songs.push({ title: value('field-title'), artist: value('field-artist'), plays: value('field-plays') }); if (activeModal === 'post') data.posts.unshift({ type: value('field-type'), status: value('field-status'), title: value('field-title'), excerpt: value('field-excerpt'), date: 'Just now' }); persist(); renderAll(); closeModal(); });
  document.addEventListener('click', function (event) { var target = event.target.closest('[data-delete-show],[data-delete-song],[data-delete-post]'); if (target) { if (target.dataset.deleteShow) data.shows.splice(Number(target.dataset.deleteShow), 1); if (target.dataset.deleteSong) data.songs.splice(Number(target.dataset.deleteSong), 1); if (target.dataset.deletePost) data.posts.splice(Number(target.dataset.deletePost), 1); persist(); renderAll(); } });
  document.querySelectorAll('.side-link[data-section], [data-jump]').forEach(function (button) { button.addEventListener('click', function () { var section = button.dataset.section || button.dataset.jump; document.querySelectorAll('.side-link[data-section]').forEach(function (link) { link.classList.toggle('active', link.dataset.section === section); }); document.querySelectorAll('.content-section').forEach(function (panel) { panel.classList.toggle('active', panel.dataset.panel === section); }); document.getElementById('page-heading').innerHTML = section === 'overview' ? 'Good morning, Thando <span>✦</span>' : section === 'schedule' ? 'Plan the day <span>✦</span>' : section === 'music' ? 'Keep it in tune <span>✦</span>' : 'Make the news <span>✦</span>'; }); });
  document.querySelectorAll('.filter-button').forEach(function (button) { button.addEventListener('click', function () { document.querySelectorAll('.filter-button').forEach(function (item) { item.classList.remove('active'); }); button.classList.add('active'); renderPosts(button.dataset.filter); }); });
}());